# Generated by Django 4.1.7 on 2023-03-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=274)),
                ('number', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField(max_length=2000)),
                ('read_status', models.BooleanField(default=False)),
            ],
        ),
    ]
