# Generated by Django 4.1.7 on 2023-03-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_contact',
            name='s',
            field=models.TextField(default='a', max_length=2000),
        ),
    ]
