# Generated by Django 4.1.7 on 2023-03-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_general_contact_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general_contact',
            name='s',
        ),
        migrations.AlterField(
            model_name='general_contact',
            name='read_status',
            field=models.TextField(max_length=2000),
        ),
    ]
