# Generated by Django 4.1.7 on 2023-03-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_general_contact_s_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_contact',
            name='message',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='general_contact',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
